GET http://localhost:5000/clientes/consulta/21781889 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFN1Y3Vyc2FsIjo1LCJ1c2VybmFtZSI6IlNVQ1VSU0FMMSIsInBhc3N3b3JkIjoicXdlcnR5IiwiaWF0IjoxNjE5MDMwNTI3LCJleHAiOjE2MjIxNDA5Mjd9.IHqM-5zXUDl-oeCb1eYaoda42vhu2WLJXLId1D52NiY