POST https://banco-vivienda.club/clientes/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer 

{
    "id" : "21781889",
    "nombres" : "Brodner",
    "primerApellido" : "Morales",
    "segundoApellido" : "Arevalo",
    "fechaNacimiento" : "1992/02/01",
    "tipoide" : 1
}